---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2022.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: traefik
      namespace: networking
    - name: metallb
      namespace: metallb-system
    - name: cert-manager
      namespace: cert-manager
  values:
    authentik:
      secret_key: "${SECRET_AUTHENTIK_SECRET_KEY}"
      postgresql:
        host: "authentik-postgresql"
        name: "authentik"
        user: "authentik"
        password: "${SECRET_AUTHENTIK_PG_PASSWORD}"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "passport"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
      - host: "id.${SECRET_DOMAIN}"
        paths:
        - path: "/"
          pathType: Prefix
      tls:
        - hosts:
            - "id.${SECRET_DOMAIN}"
          secretName: "id-tls"
    env:
      AK_ADMIN_PASS: ${SECRET_AUTHENTIK_ADMIN_PASSWORD}
      AUTHENTIK_DEFAULT_USER_CHANGE_NAME: false
      AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL: false
      AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME: false
    postgresql:
      enabled: true
      auth:
        username: authentik
        database: authentik
        password: "${SECRET_AUTHENTIK_PG_PASSWORD}"
      postgresqlPassword: "${SECRET_AUTHENTIK_PG_PASSWORD}"
      image:
        registry: ghcr.io
        repository: zcube/bitnami-compat/postgresql
        tag: 11
      # persistence:
      #   enabled: true
      #   storageClass: openebs-jiva-csi-default
    redis:
      enabled: true
      image:
        registry: ghcr.io
        repository: zcube/bitnami-compat/redis
        tag: 6.2
