---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://github.com/authelia/chartrepo/tree/master/charts
      chart: authelia
      version: 0.8.58
      sourceRef:
        kind: HelmRepository
        name: authelia-charts
        namespace: flux-system
      interval: 5m

  values:
    domain: ${SECRET_DOMAIN}

    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      subdomain: id

      tls:
        enabled: true
        secret: "authelia-tls"

    pod:
      kind: Deployment
      env:
        - name: TZ
          value: ${TIMEZONE}

      storage:
        postgres:
          enabled: true
          host: authelia-postgres.auth.svc.cluster.local
          database: postgres
          schema: postgres
          username: postgres

    configMap:
      enabled: true
      server:
        read_buffer_size: 8192
        write_buffer_size: 8192
      theme: light
      authentication_backend:
        disable_reset_password: true
        ldap:
          enabled: true
          url: ldap://dir1.${SECRET_PRIVATE_DOMAIN}
          base_dn: ${SECRET_PRIVATE_LDAP_ROOT_DN}
          username_attribute: "sAMAccountName"
          users_filter: "(&({username_attribute}={input})(objectCategory=person)(objectClass=user))"
          display_name_attribute: "displayName"
          user: "CN=IDP_SERVICE,CN=USERS,${SECRET_PRIVATE_LDAP_ROOT_DN}"
      session:
        redis:
          enabled: false

    secret:
      existingSecret: "idp-credentials"
      storage:
        key: secretIDPPGPassword
      jwt:
        key: secretIDPJWTToken
      session:
        key: secretIDPSession
      storageEncryptionKey:
        key: secretIPDStorageEncryptionKey
      ldap:
        key: secretIDPLDAPUserPassword
