# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:30AiuqiMm+0+Q1dTqsLmt9x3Mxb7BiPPiUD8Gv8=,iv:ak2/H/Mp7Q0CvE24O1hL5ldEX8k4WTkYe+k0bPYAgmc=,tag:5qTl9Ggr+MTyRBovJ2lxTg==,type:str]
    api-key: ENC[AES256_GCM,data:Mb8C0nSLUfwk/pA01fu8qxtOkDn5fZPKulGpyIXVRpl4XOjk3g==,iv:fhP455iJbyPTB+oKEIJ1W9aJf6ZS1c5G8IpjdU/OiLk=,tag:jgbRzHVdNBRyYeaU9GBi5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5anVFT0E3MEk3NVdIa09C
            TFJjejF3VHBQbEpXcUVpRzZTbUp4QkI0bTMwCkRybmd6TjlYZjgvL1lIOUpTa1JP
            RTJOWE5lbURjMndxUzUrM3N2a0haYlUKLS0tIHVvR0ppblNFUjZmTnlyWWJvNnlv
            Ym14S3QvcjNLUHBwN1hZOWhNd2R3bTAKe3GGqwbzj1zX/rey4tKWMdiGdsesqNqa
            UnhNojBgeOGpI3FJNaXf8qZtc9t57CtSYWa6sxCWUtZIZdPpJ3AkcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T15:33:25Z"
    mac: ENC[AES256_GCM,data:Fl+UlA45NfzvQZCIOdTTBBVxaYR42r9nbqjPueWbsMrjUMNNj9BbXEagQGt65IOcNV5Fogx7ZPMVX2EEIndU2wsOsN9wpTyVII35sPZKMWu4gSmRiRba7smtmeyDqw4fBlKndb8RG4hOFMsG/SR6WR7zlRX8jqVDqDAi0yc6EVU=,iv:xWGT+NvtHGclQSsIrVVTW+AzHePmLuPYGJX08na7uxc=,tag:hdyy7lb3BsffvEDmFe23mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
