# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:tzcVA19WKtFCW/HOdCP5,iv:UKvTyYhH5Rvha7fGdLHqf4j+AjKtKNxBO07OjnayvD8=,tag:GjeL4QbsktSD/4rjw7Rahg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JGV26OezjcxsztlXhHaP4lxutr0KpaEguokBXVg=,iv:j+DcTRYlneb3hdad9XQqWpSutflLewQS8iOdu/LGSFc=,tag:9seYtCOQK8C2XJ2g4fT8Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZng0ZWNJWUNEOFV1MWxh
            QWhWTHlNM2R4NEZXaG1pZkIwUENWZk04cERvClhydnBHaVJLNWlQNEpyZ3BWRXBm
            SFZGZFppY1VXaU84anozSWVHS08wc2cKLS0tIDVaUjUwTDY0RjdERjRHb3BlclBt
            RUpOa3kzUXhHUEtNN2xCTlFDZXpocDAKB8Vo+J/OH1ycNNSpsS3Pkl/fx8TWcrkP
            VSLR/5Ma0AEmwqlYISkg1NgDv7FABIs6vHDVHql5Jrhc9NqG2Dgifw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T15:33:25Z"
    mac: ENC[AES256_GCM,data:jaZjLU6fEzu8QG5j5v0juHMD+qm7ai6xbYAmC96RoK6zsqgQqQ8rZJvPZgX1VIz2ElFPYumIKlaHJJ1V74HADfmq1zPAZCW7WvzxiO+5CZDWMTB/Uq1B7du3FuNLb8AFW8a9x0E7qLpS3QLLCgS5Bzew3qmmwB6nX/VmdGSickQ=,iv:Zio/PEdUDxXCmxtV+tK063HdbkJRPGCyJQhV1yn0XOo=,tag:DVmaQ6VBjtkMOTDjCoCLlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
