---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Paris
  METALLB_LB_RANGE: 10.17.0.50-10.17.0.99
  METALLB_K8S_GATEWAY_ADDR: 10.17.0.51
  METALLB_INGRESS_ADDR: 10.17.0.50
  METALLB_CHRONY_ADDR: 10.17.0.52
  METALLB_MQTT_ADDR: 10.17.0.53
  METALLB_BLOCKY_ADDR: 10.17.0.54
