---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 20m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: metallb
      namespace: metallb-system
  values:
    env:
      TZ: Europe/Paris
    controller:
      replicas: 1
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
    service:
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${METALLB_BLOCKY_ADDR}"
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${METALLB_BLOCKY_ADDR}"
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 250m
        memory: 250Mi
    autoscaling:
      enabled: True
      target:  blocky
      minReplicas:  1
      maxReplicas:  3
      targetCPUUtilizationPercentage:  80
      targetMemoryUtilizationPercentage:  90
    redis:
      enabled: true
      env:
        TZ: Europe/Paris
      image:
        registry: ghcr.io
        repository: zcube/bitnami-compat/redis
        tag: 6.2
      master:
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 250m
            memory: 16Mi
          limits:
            cpu: 500m
            memory: 32Mi
      replica:
        replicaCount: 1
        persistence:
          enabled: false
        autoscaling:
          enabled: True
          targetCPU: 50
          targetMemory: 75
        resources:
          requests:
            cpu: 250m
            memory: 16Mi
          limits:
            cpu: 500m
            memory: 32Mi
      auth:
        enabled: false
        sentinel: false
      sentinel:
        enabled: True
        image:
          registry: ghcr.io
          repository: zcube/bitnami-compat/redis-sentinel
          tag: 6.2
        resources:
          requests:
            cpu: 125m
            memory: 8Mi
          limits:
            cpu: 250m
            memory: 16Mi
      metrics:
        enabled: false
        image:
          registry: ghcr.io
          repository: zcube/bitnami-compat/redis-exporter
          tag: 1
    config: |
      upstream:
        default:
        - https://dns1.nextdns.io/4838af
        - https://dns2.nextdns.io/4838af
        - tcp-tls:4838af.dns1.nextdns.io:853
        - tcp-tls:4838af.dns2.nextdns.io:853
        - 46.182.19.48
        - 80.241.218.68
        - tcp-tls:fdns1.dismail.de:853
        - https://dns.digitale-gesellschaft.ch/dns-query
        - tcp+udp:208.67.220.220
        - tcp+udp:208.67.220.222
        - tcp+udp:8.8.4.4
        - tcp+udp:8.8.8.8
      conditional:
        mapping:
          ${SECRET_PRIVATE_DOMAIN}: tcp+udp:10.1.0.4
          ${SECRET_DOMAIN}: tcp+udp:k8s-gateway
          0.1.10.in-addr.arpa: tcp+udp:10.1.0.4
          1.1.10.in-addr.arpa: tcp+udp:10.1.0.4
      blocking:
        blackLists:
          ads:
            - https://dbl.oisd.nl/
            # - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
            - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
            - http://sysctl.org/cameleon/hosts
            - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
            - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
          special:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
        clientGroupsBlock:
          default:
          - ads
          - special
      logLevel: info
      httpPort: 4000
      clientLookup:
        upstream: tcp+udp:10.1.0.4
      prometheus:
        enable: true
        path: /metrics
      # queryLog:
      #   type: mysql
      #   target: ${SECRET_BLOCKY_DB_USER}:${SECRET_BLOCKY_DB_PASSWORD}@tcp(blocky-mariadb:3306)/${SECRET_BLOCKY_DB}?charset=utf8mb4&parseTime=True&loc=Local
      #   logRetentionDays: 7
      redis:
        address: blocky-redis-headless:6379
        required: true
        connectionAttempts: 10
        connectionCooldown: 3s
        database: 2
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    # metrics:
    #   enabled: true
