---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: mosquitto
      version: 4.7.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: metallb
      namespace: metallb-system
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${METALLB_MQTT_ADDR}"
        externalTrafficPolicy: Local
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClassName: local-path
      configinc:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClassName: local-path

    resources:
      requests:
        cpu: 75m
        memory: 64Mi
      limits:
        memory: 128Mi
