---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: coredns
      version: 1.19.4
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
