---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: searxng
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: metallb
      namespace: networking
    - name: cert-manager
      namespace: kube-system
  values:
    env:
      TZ: ${TIMEZONE}
      INSTANCE_NAME: "my-instance"
      BASE_URL: "http://search.${SECRET_DOMAIN}/"
      AUTOCOMPLETE: true
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: "magnify"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "search.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "search.${SECRET_DOMAIN}"
            secretName: "searxng-tls"
